# -*- coding: utf-8 -*-
"""udemy.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10xNWZznSAEzSLgNxi-xzwvc5DNEKUW3Y
"""

import pandas as pd

data = pd.read_csv(r"/content/7. Udemy Courses.csv")

data.head()

"""What are all different subjects for which udemy is offering courses?"""

data.subject.unique()

"""Which subject has the maximum number of courses?

"""

data.head(2)

data.subject.value_counts()

"""Show all the courses which are free of cost"""

data[data.is_paid == False ]

"""show all the courses which are paid"""

data[data.is_paid == True]

"""Which are Top selling courses?"""

data.sort_values('num_subscribers',ascending = False)

"""Which are least selling courses?"""

data.sort_values('num_subscribers')

"""Show all courses of graphic Design where the price is below 100?"""

data[(data.subject == 'Graphic Design')&(data.price<'100')]

data[(data.subject == 'Graphic Design')&(data.price=='100')]

"""List out all the courses that are related with 'Python'"""

data.head(1)

data[data.course_title.str.contains('Python')]

"""What are courses that published in year 2015?"""

data.dtypes

data['published_timestamp'] = pd.to_datetime(data.published_timestamp)

data.dtypes

data['Year']= data['published_timestamp'].dt.year

data

data[data.Year == 2015]

"""What are the Max. Number of subscribers for Each Level of courses?"""

data.level.unique()

data.groupby('level')['num_subscribers'].max()

data.groupby('level')['num_subscribers'].min()

data.groupby('level').max()